### PR TITLE
Loader added

### PR DESCRIPTION
**Pull request by AlonaVladymyrovaTrinity**
Loader component successfully created. 
This is functional styled 'Loader' component that displays a spinner with optional size variations based on the given class name.

### CODE REVIEW

**Comment by badgerbadgers** [comment]
Is there any page I can view the animation in action? Or this was uploading the loading animation and component.

**Review by badgerbadgers — APPROVED** [review]
LGTM can't wait to see this in action!

**Comment by badgerbadgers** [comment]
Would also comment out the async  function in the app.js lines 11-14 with another commit.

**Comment by AlonaVladymyrovaTrinity** [comment]
it's just a reusable component with a spinner that can be used on absolutely any page of our application(and we can do it smaller size by passing className "small-spinner" into it. Like this <StyledSpinner className="small-spinner" />). We plan to use it on the main page that Luba is working on. So you will be able to see it in the Action after Luba completes the homepage.

**Comment by AlonaVladymyrovaTrinity** [comment]
I didn't add any changes to the app.js file with this commit

**Comment by LiubovCass** [comment]
Everything looks good Alena!

**Review by LiubovCass — APPROVED** [review]

**Pull request merged**
