### PR TITLE
Pp 74 navigate button

### PR DESCRIPTION
**Pull request by LiubovCass**
Created the NavigateButton which let us navigate to another page in our app.

### CODE REVIEW

**Review by AlonaVladymyrovaTrinity — APPROVED** [review]
LGTM!

**Review by arigakova — APPROVED** [review]

**Review by badgerbadgers — APPROVED** [review]
LGTM great to see reusable components in your app.

**Comment by badgerbadgers** [comment]
Screenshot 2023-05-24 at 6 44 35 PM
Looks great. 

For the PR some instructions and description would be great next time.

**Example:**
Description:
This is a reusable navigation component! It is designed to be used throughout the app and is located in the components folder. Please see QA instructions to test it out!

QA Instructions:
- run `npm install`
- the component is located in the components folder. /src/components/layout/NavigateButton.js
- in file (filename.js) you can test this component out by first importing the navigation button:
- `import NavigateButton from "./component/layout/NavigateButton"`
- now create the component as a self closing component: `<NavigateButton />`
- maybe include a screenshot of what the component looks like if it will affect the ui.
Screenshot 2023-05-24 at 6 54 43 PM

Great work on this button! I can't wait to see more of the app! I see you have organized your css files also, it's all coming together now.

**Comment by LiubovCass** [comment]
Great point Tim. Thank you for suggestions

**Pull request merged**
