### PR TITLE
PP-15-contact-page

### PR DESCRIPTION
**Pull request by arigakova**

### CODE REVIEW

**Comment by badgerbadgers** [comment]
I'd include some text to navigate to http://localhost:3000/contact to see new page in PR writeup. Look great!

**Review by badgerbadgers — APPROVED** [review]
LGTM!

**Comment by arigakova** [comment]
> I'd include some text to navigate to http://localhost:3000/contact to see new page in PR writeup. Look great!

I'm sorry, but I did not understand what and where I could add?

**Review by MunirNuristani — APPROVED** [review]
LGTM!
Impressive Work.

**Comment by badgerbadgers** [comment]
> > I'd include some text to navigate to http://localhost:3000/contact to see new page in PR writeup. Look great!
> 
> I'm sorry, but I did not understand what and where I could add?

In description of the PR for next time: if the page is viewable in the app a link would be helpful for the reviewer to view the page.

**Review by AlonaVladymyrovaTrinity — COMMENTED** [review]
Please, refactor the code:
Replace the file name Contact.css with Contact.module.css
In file Contavt.js: replace line 
import './Contact.css';
with 
import style from './Contact.module.css'

And apply all additional changes in this file accordingly.
For example line 10: `<div className="background-container">`
should look like: `<div className={style['background-container']}>`

**Review by AlonaVladymyrovaTrinity — CHANGES_REQUESTED** [review]
Once the necessary changes have been made, I will approve it.

**Comment by arigakova** [comment]
> Once the necessary changes have been made, I will approve it.

Requested change has been made.

**Review by AlonaVladymyrovaTrinity — APPROVED** [review]

**Pull request merged**
