### PR TITLE
PP-57 Create pets page

### PR DESCRIPTION
**Pull request by LiubovCass**
Description:
This is The Pets page of our App. http://localhost:3000/pets
QA Instructions:

The Pets page consists of PetCard Component, Grid of PetCard, Header, Footer, banner with video and NavigationButton Component and filters(select elements) for choosing a pet.
The Pet Cards are links to Pets Details Page (http://localhost:3000/pet/cat%60). The petCard consists heart checkbox for checkmark favorites pets. 

image
(I’m not sure if picture shows up correctly )

### CODE REVIEW

**Comment by LiubovCass** [comment]
I believe npm install will help.

**Review by AlonaVladymyrovaTrinity — APPROVED** [review]
Awesome job! The heart checkbox for favorites is really cool!

**Review by OxiBo — APPROVED** [review]
Everything looks good and works as it supposed to at this point. Please keep in mind for the future fixes some responsive issues on the page at this point

**Comment by LiubovCass** [comment]
for install fontawesome:
npm i --save @fortawesome/fontawesome-svg-core
npm install --save @fortawesome/free-solid-svg-icons
npm install --save @fortawesome/react-fontawesome

**Pull request merged**
