### PR TITLE
PP-89: Add functionality to User Update Profile page. Formatting the …

### PR DESCRIPTION
**Pull request by AlonaVladymyrovaTrinity**
Add functionality to User Update Profile page. Formatting the date string on Profile page implemented. Added logout function on Profile page.

**This pull request include the following updates:**
- Configured Axios for user actions: logout and updateUserProfile.
- Implemented the reducer function profileReducer to handle different actions.
- Added functionality to User Update Profile page [http://localhost:3000/me/update](http://localhost:3000/me/update):
> - Implemented formatting for the date string on the Profile page.
> - Added a logout function on the Profile page.
- Updates in the Profile component:
> - Modified the logout action handling.
> - Displayed the joined date with formatted and relative time.
- Updates in the UpdateProfile component:
> - Implemented form submission handling.
> - Displayed error and success messages.

**Testing instructions:**
Install:
- npm install
- npm install moment date-fns
- Pay special attention to the changes made in the Profile.js and UpdateProfile.js files.
- Test the updated profile functionality by submitting the form with valid or invalid data and verifying the success or error messages.
- Check if the profile information is updated correctly after submitting the form.
- Ensure that any error messages or success messages related to the current pull request are displayed correctly.
- Test the logout functionality by clicking the logout button and ensuring that the user is successfully signed out and redirected to the home page.

User Update Profile Page

### CODE REVIEW

**Review by LiubovCass — APPROVED** [review]
LGTM!

**Comment by badgerbadgers** [comment]
Possible UI improvements:
- when updating profile can have message in the missing text input field with red text (name and/or email) should be entered. Can be required field.
Screenshot 2023-06-13 at 6 38 29 PM

-when user is logged in the login can now display the user's displayname, easier is probably just hide the login button in the navbar if user is signed.
Screenshot 2023-06-13 at 6 40 58 PM

- Test the updated profile functionality by submitting the form with valid or invalid data and verifying the success or error messages. [x]
- Check if the profile information is updated correctly after submitting the form. [x]
- Ensure that any error messages or success messages related to the current pull request are displayed correctly. [x]
- Test the logout functionality by clicking the logout button and ensuring that the user is successfully signed out and redirected to the home page. [x]

**Review by badgerbadgers — APPROVED** [review]
LGTM! works well no errors and wrote some UI suggestions.

**Comment by AlonaVladymyrovaTrinity** [comment]
Thank you for your review and recommendations! We will try to fix all this in the future...

**Pull request merged**
