### PR TITLE
PP-102: Pictures in cards on Home page and Pets page fixed in accordance with…

### PR DESCRIPTION
**Pull request by AlonaVladymyrovaTrinity**
… the updated DB scheme and data from database

Pictures in cards on Home page and Pets page fixed in accordance with the updated DB scheme and updated data from database

Screenshot 2023-06-16 at 1 35 06 PM

### CODE REVIEW

**Review by LiubovCass — APPROVED** [review]
LGTM

**Comment by badgerbadgers** [comment]
Screenshot 2023-06-16 at 6 42 28 PM
This is an issue worth looking into. When viewing Pets page there are 200 alerts in console.log. Probably duplicate keys when fetching data from your database.

**Review by badgerbadgers — APPROVED** [review]
LGTM, left comment about issue with id.

**Comment by AlonaVladymyrovaTrinity** [comment]
We will try to fix this issue after the merge.

**Pull request merged**
