### PR TITLE
PP-64: Create Login/SignUp page.

### PR DESCRIPTION
**Pull request by AlonaVladymyrovaTrinity**
**PP-64: Create UI for Login/SignUp page:**
        

React component for a login and sign-up form. The component includes functionality for switching between login and register tabs, handling form submissions. It also includes conditional rendering based on a server loading state simulation.

The component uses various React packages and components such as useState, Link, FontAwesomeIcon, Loader, and InputWithIcon to create a user-friendly login and sign-up interface. The login form captures and logs the login email and password to the console(for testing), while the register form creates a FormData object and logs the form data to the console(for testing).

The component also includes an avatar preview feature that allows users to select an image file as their avatar.

Overall, this component provides a basic structure for a login and sign-up form with input validation, conditional rendering, and form submission handling.

        **Created new component LoginSignUp:**
        new file:   src/component/User/LoginSignUp.css
        modified:   src/component/User/LoginSignUp.js
        
        **Created new component InputWithIcon for Login/SignUp page:**
        new file:   src/component/layout/InputWithIcon/InputWithIcon.css
        new file:   src/component/layout/InputWithIcon/InputWithIcon.js
        
        **Added new picture for Login/SignUp page:**
        new file:   src/images/Profile.png
                
        **Fixed small bugs on:**        
        modified:   src/component/layout/Header/Header.js
        modified:   src/component/layout/NotFound/NotFound.css
        modified:   src/component/Donate/Donate.js

### CODE REVIEW

**Review by badgerbadgers — APPROVED** [review]
LGTM! I'd just include instructions after the description `npm install` to install any dependencies. Great job! Its really coming along!

**Review by LiubovCass — APPROVED** [review]
It looks good to me! Great job Alona

**Review by arigakova — APPROVED** [review]
Great Job, Alona!

**Review by MunirNuristani — APPROVED** [review]
LGTM! Great Work!!!!!

**Pull request merged**
