### PR TITLE
PP-78 CSS Login/SignUp Page was improved

### PR DESCRIPTION
**Pull request by LiubovCass**
CSS for Login/SignUp Page was improved. Fixed cursor pointer on Login and Register buttons (on hover).
Some minor fixes was added to css files for Home page and Pets page.

### CODE REVIEW

**Review by AlonaVladymyrovaTrinity — APPROVED** [review]
Great job on CSS! 
I really glad to see that you was able to fix this tricky bug with cursor pointer on Login/SignUp page and I really like the layout of cards on the homepage now. Hearts and cards are responsive now! Awesome work!

**Comment by LiubovCass** [comment]
Added improvements to User Update Page Css. PP-82

**Review by badgerbadgers — APPROVED** [review]
LGTM! This all looks amazing!

**Comment by badgerbadgers** [comment]
For next time some screenshots (and links to the pages you worked) for UI updates and changes would look great in your PR, love the heart icon animation when you favorite a pet! Show the reviewer all the hard work you did! This is some great attention to detail!

Screenshot 2023-06-08 at 7 04 51 PM

**Pull request merged**
