### PR TITLE
PP-83: added functionality to login sign up page

### PR DESCRIPTION
**Pull request by AlonaVladymyrovaTrinity**
**Pull Request Description:**

This pull request introduces a new feature that enhances the user authentication and registration process in our application. It includes the implementation of a login and registration form with improved user experience and error handling.

**Key Changes:**

1. Improved a LoginSignUp component that handles the login and registration functionality.
2. Implemented tab switching between the registration and login forms for easy user navigation: when the user is successfully registered the tab is switching from registration and login.
3. Utilized the react-bootstrap library to display success and error messages using the Alert component.
4. Integrated API calls for login and registration using the axios library.
5. Implemented a reducer function and dispatched actions to update the state based on the API responses.
6. Utilized cookies to store and retrieve the user's authentication token.
7. Added a proxy middleware sets up to forward requests from the '/api' endpoint to a target server at 'http://localhost:8000/'.

**Steps for QA Testing:**

1. Install: 
 > 1. `npm install axios@1.4.0 npm `
 > 2. `install http-proxy-middleware`
 > 3. `npm install js-cookie react-router-dom npm `
 > 4. `install react-bootstrap@latest bootstrap@latest`

2. Run the app `npm start`
3. Open the application and navigate to the login and registration pages: [http://localhost:3000/login](http://localhost:3000/login)
4. Verify that both the login and registration forms are displayed correctly.
5. Test switching between the login and registration tabs and ensure that the form content updates accordingly.
6. Submit the login form with valid credentials and verify that the user is successfully logged in and ensure that the user is redirected to the user profile page (http://localhost:3000/account).
7. Submit the login form with invalid credentials and ensure that the appropriate error message is displayed.
8. `Check that the user with name Joe Biden can register on the site by entering only his first name.`
9. Fill out the registration form with valid data and submit it to create a new user account.
10. Verify that the success message is displayed and the user is redirected to the login tab.
11. Attempt to register with an existing email address and verify that the error message is displayed.
12. Test form validation by leaving required fields empty and verify that the corresponding error messages are shown.

### CODE REVIEW

**Review by OxiBo — APPROVED** [review]
Great job! Glad to see that login/register functionality has been implemented. I do have to mention that it is a big PR which could and should have been broken in smaller pieces. Just like it describes the key changes in the description it could have been about 7 different PR (as the key changes description). 
LoginSignUp.js component has a few typos which would be nice to correct (I won't be requiring this now, just look into it when you have time).
One improvement I do suggest: after user get registered, it is better user experience to log them in right away instead of pointing to the login window.
Overall, great job! You have done a big chunk of work!

**Comment by AlonaVladymyrovaTrinity** [comment]
> Great job! Glad to see that login/register functionality has been implemented. I do have to mention that it is a big PR which could and should have been broken in smaller pieces. Just like it describes the key changes in the description it could have been about 7 different PR (as the key changes description).

Thanks for the recommendation, now I will know how to split code into smaller pull requests in this case.

> LoginSignUp.js component has a few typos which would be nice to correct (I won't be requiring this now, just look into it when you have time).

Fixed.

> One improvement I do suggest: after user get registered, it is better user experience to log them in right away instead of pointing to the login window.

Thanks for the suggestion. It's even easier to implement, than logic which was done before, so it was a very easy fix. Done!

> Overall, great job! You have done a big chunk of work!

Thanks!

**Review by OxiBo — APPROVED** [review]
Great job! Now when you have cookies set up and working you can also work on displaying the right navigation items in the header (show logOut if user logged in) and implement redirect if logged in user is trying to access /login page; implement logout functionality!

**Review by arigakova — APPROVED** [review]

**Review by LiubovCass — APPROVED** [review]
Great functionality! I tried to register user Joe, but got message "Name cannot have less than 4 characters". I think it would  be better to change this restriction.

**Comment by AlonaVladymyrovaTrinity** [comment]
Thank you very much for bringing this to our attention. In case we will decide to make these changes, it will be necessary to make appropriate adjustments on the backend side.

**Pull request merged**
