### PR TITLE
PP-91-Pets-page-successfully-connected-with-back-end

### PR DESCRIPTION
**Pull request by AlonaVladymyrovaTrinity**
This pull request adds functionality to retrieve all pets from the API and display them on the Pets page [http://localhost:3000/pets](http://localhost:3000/pets). It includes a new file petAction.js that contains the getPet function, which makes an API request to fetch all pets. The response data is then dispatched to update the state in the petsReducer file.

Additionally, the PetCard component has been modified to accept a pet prop and display the pet's information, such as name, gender, age, color, and breed. The component also dynamically loads different images based on the pet's type (cat or dog).

**Testing Instructions:**

- Install the necessary dependencies by running npm install in the project directory.
- Verify that the Pets page [http://localhost:3000/pets](http://localhost:3000/pets) displays a loader while the pets are being fetched.
- Once the pets are loaded, ensure that the pet cards are displayed with the correct information (name, gender, age, color, and breed).
- Check that the pet images are loaded correctly based on the pet's type (cat or dog).

Pets Page

### CODE REVIEW

**Comment by badgerbadgers** [comment]
At around 1079px to 997px the pet images start to overlap, definitely not a priority to work on just something I noticed.
Screenshot 2023-06-14 at 7 52 16 PM

Love the responsiveness of the pet image gallery! Again slick use of images for pets with no picture. Great work!

**Review by badgerbadgers — APPROVED** [review]
LGTM! No errors when fetching data.

**Comment by AlonaVladymyrovaTrinity** [comment]
Thank you for letting us know! 
I added this issue to our backlog.

**Review by LiubovCass — APPROVED** [review]
Looks great Alona!

**Pull request merged**
