### PR TITLE
PP 126 create success donation page

### PR DESCRIPTION
**Pull request by LiubovCass**
Success donation page was created.

### CODE REVIEW

**Review by AlonaVladymyrovaTrinity — APPROVED** [review]
LGTM

**Comment by badgerbadgers** [comment]
Screenshot 2023-07-04 at 5 43 38 PM
All these screens look so sharp! I would say you could just have the success message and not the long form text in this screen. The text can probably be in the donation page. Just a suggestion love these images.

**Review by badgerbadgers — APPROVED** [review]
LGTM!

**Comment by AlonaVladymyrovaTrinity** [comment]
This is a very good idea, however, there is very little time left before the end of practicum and we still have a lot to do, so most likely we will not have time to make these changes.

**Pull request merged**
