### PR TITLE
PP-107-Connect-add-to-favorites-button-on-pet-details-page-with-back-end

### PR DESCRIPTION
**Pull request by arigakova**
PetAction:
The provided code includes several functions related to managing favorite pets. 
getAllFavorites: This function retrieves all favorite pets.  
addPetToFavoritesOnPets: This function adds a pet to the favorites list. 
removePetFromFavoritesOnPets: This function removes a pet from the favorites list. 

Favorite Pets:
If the user is not authorized when clicking on the add to favorite pet button,  he is redirectered to the login page.
Home:
Refactiring Home page. List of pets on Home page had the same functionality as Pets component except filtering on Pets component. Due to that fact Pets component was re-used on Home page and filtering was made conditional in Pets component. Home page disables filtering by means of new param for Pets component showFilters.
PetCard: 
 This code snippet utilizes the AuthContext to access the userId and conditionally display the favorite state based on the user's authentication status. When the user is authenticated  the isFavoriteHidden state is updated to false, enabling the display of the favorite state. 
If the user  is authorized,  when you click on the heart, the animal will be added to the favotites on the pages of Home and Pets.

PetDetails:
This code snippet utilizes hooks like useMemo, useState, useEffect, useNavigate, and useContext to handle state, navigation, and fetching pet data. It checks the authentication status of the user based on the userId, sets the isAuthenticated state accordingly, and fetches pet data and favorite status based on the provided id and authentication status.

Pets:
This useEffect hook ensures that when the authentication status (isAuthenticated) changes and the user is authenticated, it triggers the fetching of all favorites by calling the getAllFavorites function.

### CODE REVIEW

**Comment by AlonaVladymyrovaTrinity** [comment]
So COOL!!! Awesome work!!! 
Screenshot 2023-06-27 at 9 02 42 PM
Screenshot 2023-06-27 at 9 02 52 PM

**Review by AlonaVladymyrovaTrinity — APPROVED** [review]
LGTM!!!! Great job!!!!

**Comment by badgerbadgers** [comment]
Looks great works as intended! Might be issue with images not loading just heads up.

Screenshot 2023-06-27 at 9 12 23 PM

**Review by badgerbadgers — APPROVED** [review]
LGTM! Left comment about possible issue with images, really great job making a favorites pet functionality work now!

**Pull request merged**
