### PR TITLE
PP-115 Heart icon and LogOut Link was added to navigation menu

### PR DESCRIPTION
**Pull request by LiubovCass**
Heart icon and LogOut Link was added to navigation menu
Desctop version
LogIn Desctop
Mobile version
LogIn Mobile
This two versions below are for Logged Out user:
Desctop version
LogOut Desctop
Mobile version
LogOut Mobile
Also some Accessibility attributes was added to Application form:
 src/component/Adoption/ConfirmApplication.js
and Profile page:
src/component/User/Profile.js

### CODE REVIEW

**Review by AlonaVladymyrovaTrinity — APPROVED** [review]
LGTM

**Comment by badgerbadgers** [comment]
Looks great! The `z-index` for the menubar could be higher so that when the menu is expanded you do not see the form menu. Might need to play around with those properties at a later time.
Screenshot 2023-06-30 at 6 03 35 PM

**Review by badgerbadgers — APPROVED** [review]
LGTM!

**Comment by LiubovCass** [comment]
@badgerbadgers thank you. Great point. This issue was fixed in PR-66
https://github.com/Code-the-Dream-School/cc-prac-team4-front/pull/66
and now it was merged to the branch PP-115.

**Pull request merged**
