### PR TITLE
PP-128-fix-visual-UI-glitch-on-favorites-page-when-loading

### PR DESCRIPTION
**Pull request by arigakova**

### CODE REVIEW

**Review by AlonaVladymyrovaTrinity — APPROVED** [review]
LGTM

**Comment by badgerbadgers** [comment]
Minor heads up with unique key prop error, easy fix with `key={pet._id}` in FavoritePet.js in the jsx line 91 when the fav pets get mapped, if yall dont have this fixed in other branches already.
Screenshot 2023-07-05 at 8 11 04 PM

**Review by badgerbadgers — APPROVED** [review]
LGTM!

**Comment by arigakova** [comment]
Good catch, Thanks! Fixed!

**Pull request merged**
