### PR TITLE
PP-120-Add-focus-visited-active-hover-to-all-buttons

### PR DESCRIPTION
**Pull request by arigakova**

### CODE REVIEW

**Comment by badgerbadgers** [comment]
Screenshot 2023-06-30 at 6 11 30 PM
Screenshot 2023-06-30 at 6 13 25 PM

When hovered over 'adopt' color is different from 'Add to favorites' button hover color. If this was by choice then disregard comment.

**Review by badgerbadgers — APPROVED** [review]
LGTM!

**Comment by arigakova** [comment]
> LGTM!

**Comment by arigakova** [comment]
> Screenshot 2023-06-30 at 6 11 30 PM Screenshot 2023-06-30 at 6 13 25 PM
> When hovered over 'adopt' color is different from 'Add to favorites' button hover color. If this was by choice then disregard comment.

Button color when hovering is fixed in another PR raised by Alona 
https://github.com/Code-the-Dream-School/cc-prac-team4-front/pull/69

**Review by AlonaVladymyrovaTrinity — APPROVED** [review]
LGTM!

**Pull request merged**
