### PR TITLE
PP-61: Created User Update Password page plus added functionality to it

### PR DESCRIPTION
**Pull request by AlonaVladymyrovaTrinity**
**Created User Update Password page plus added functionality to it.** 

**Pull Request Description:**

**This pull request includes the following changes:**

Added a new function updateUserPassword in the user actions file (userAction.js) to handle updating user passwords. The function takes oldPassword, newPassword, setErrorMessage, and dispatch as parameters and makes a PATCH request to the endpoint with the old and new passwords. It dispatches actions based on the success or failure of the request and logs the response message for testing purposes.

Updated the CSS styles in the following files: ForgotPassword.module.css, LoginSignUp.module.css, Profile.module.css, UpdateProfile.module.css
UpdatePassword.module.css: Added new CSS file with styles for the UpdatePassword component.

Updated the UpdatePassword component:
Imported necessary dependencies and components.
Defined initial state and reducer using useReducer.
Defined state variables and event handlers.
Added a form submission function updatePasswordSubmit to handle updating the password. It checks if the new password matches the confirm password and calls the updateUserPassword function to make the API request. It also handles success and error messages.
Rendered success and error messages using Alert components.
Added CSS styles for the component using the UpdatePassword.module.css file.

**Testing Steps:**

**Install:** 
npm install @fortawesome/free-solid-svg-icons @fortawesome/react-fontawesome 
npm install @mdi/font @mdi/react
npm install @mdi/react @mdi/js

Run the application with these changes.
Open page [http://localhost:3000/password/update](http://localhost:3000/password/update)
Verify that the updateUserPassword function successfully updates the user's password when called with valid parameters.
Verify that the success message is displayed when the password is updated successfully.
Verify that the error message is displayed when there is an error updating the password.
Verify that the CSS styles for the updated components and buttons are applied correctly, including hover, focus, and active states.

Screenshot 2023-06-27 at 1 31 18 AM

### CODE REVIEW

**Review by arigakova — APPROVED** [review]
LGFM

**Comment by badgerbadgers** [comment]
Looks good and works well!
Now that there's two weeks left and it's last sprint maybe worth now looking at and breaking the app with different actions, viewports and add styling for stuff that the front end team can get to! 

I'm sure you have this as a standing ticket on your board.
Screenshot 2023-06-27 at 7 49 51 PM

**Review by badgerbadgers — APPROVED** [review]
Great job! Works well this is a beefy PR lots of hard work done!

**Comment by AlonaVladymyrovaTrinity** [comment]
>Now that there's two weeks left and it's last sprint maybe worth now looking at and breaking the app with different actions, viewports and add styling for stuff that the front end team can get to!
>I'm sure you have this as a standing ticket on your board.

Yes, we have this issue in our todo list! Luba is assigned on this issue and she will start working on it soon.)

**Comment by AlonaVladymyrovaTrinity** [comment]
Thanks!

**Pull request merged**
