### PR TITLE
PP-93 Home page Connected with back-end and some css changes

### PR DESCRIPTION
**Pull request by LiubovCass**
This pull request adds functionality to retrieve all pets from the API and display them on the Home page http://localhost:3000. The response data from file petAction.js is dispatched to update the state in the petsReducer file witch used on Home page.

Testing Instructions:

Install the necessary dependencies by running npm install in the project directory.
Verify that the Home page http://localhost:3000 displays a loader while the pets are being fetched.
Once the pets are loaded, ensure that the pet cards are displayed with the correct information (name, gender, age, color, and breed).
Ensure that the Pagination is displayed and working properly.
Check that the pet images are loaded correctly based on the pet's type (cat or dog).

Modified files:

Home page was connected with back-end:
src/component/Home/Home.js

Minor changes to css added:
src/component/Home/Home.module.css
src/component/User/ForgotPassword.module.css
src/component/User/UpdateProfile.module.css
src/component/layout/Footer/Footer.module.css
 src/component/layout/Header/Header.module.css
src/index.css

Navigation link was modified:
   src/component/Home/PetCard.js

Code was cleaned:
src/component/Pet/Pets.js

Code was prepared for future modifications:
 src/component/layout/FavoriteCheckbox/FavoriteCheckbox.js
src/component/layout/Header/Header.js

HomePage

### CODE REVIEW

**Review by AlonaVladymyrovaTrinity — APPROVED** [review]
Awesome work!!!

**Comment by badgerbadgers** [comment]
This looks excellent!

**Comment by badgerbadgers** [comment]
There does seems to be some duplicate pets that show up a few times. This could be an issue you can create and look into later on.

Screenshot 2023-06-15 at 3 55 24 PM

Screenshot 2023-06-15 at 3 54 53 PM

Screenshot 2023-06-15 at 3 58 47 PM

**Review by badgerbadgers — APPROVED** [review]
LGTM, great work there is now data from the backend being displayed on the Home Page and it looks awesome! Left a comment that you could look into for next time.

**Comment by AlonaVladymyrovaTrinity** [comment]
Thanks for reporting this issue. We will try to find the reason why it occurs.

**Pull request merged**
